/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vijay
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static String action = "";

    private static double num1 = 0;
    private static double num2 = 0;
   private static double result = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        abt = new javax.swing.JTextField();
        ab1 = new javax.swing.JButton();
        ab2 = new javax.swing.JButton();
        ab6 = new javax.swing.JButton();
        ab3 = new javax.swing.JButton();
        ab4 = new javax.swing.JButton();
        ab7 = new javax.swing.JButton();
        ab5 = new javax.swing.JButton();
        abo = new javax.swing.JButton();
        ab8 = new javax.swing.JButton();
        abp = new javax.swing.JButton();
        abmi = new javax.swing.JButton();
        ab9 = new javax.swing.JButton();
        abequal = new javax.swing.JButton();
        abb2 = new javax.swing.JButton();
        abg1 = new javax.swing.JButton();
        abc = new javax.swing.JButton();
        abl = new javax.swing.JButton();
        abdo = new javax.swing.JButton();
        aboo = new javax.swing.JButton();
        absq1 = new javax.swing.JButton();
        abr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });

        ab1.setText("1");
        ab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab1ActionPerformed(evt);
            }
        });

        ab2.setText("2");
        ab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab2ActionPerformed(evt);
            }
        });

        ab6.setText("6");
        ab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab6ActionPerformed(evt);
            }
        });

        ab3.setText("3");
        ab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab3ActionPerformed(evt);
            }
        });

        ab4.setText("4");
        ab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab4ActionPerformed(evt);
            }
        });

        ab7.setText("7");
        ab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab7ActionPerformed(evt);
            }
        });

        ab5.setText("5");
        ab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab5ActionPerformed(evt);
            }
        });

        abo.setText("0");
        abo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboActionPerformed(evt);
            }
        });

        ab8.setText("8");
        ab8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab8ActionPerformed(evt);
            }
        });

        abp.setText("+");
        abp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abpActionPerformed(evt);
            }
        });

        abmi.setText("-");
        abmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmiActionPerformed(evt);
            }
        });

        ab9.setText("9");
        ab9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab9ActionPerformed(evt);
            }
        });

        abequal.setText("=");
        abequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abequalActionPerformed(evt);
            }
        });

        abb2.setText("%");
        abb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abb2ActionPerformed(evt);
            }
        });

        abg1.setText("*");
        abg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abg1ActionPerformed(evt);
            }
        });

        abc.setText("CLR");
        abc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abcActionPerformed(evt);
            }
        });

        abl.setText("(");
        abl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ablActionPerformed(evt);
            }
        });

        abdo.setText(".");
        abdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abdoActionPerformed(evt);
            }
        });

        aboo.setText("00");
        aboo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abooActionPerformed(evt);
            }
        });

        absq1.setText("SQRT");
        absq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absq1ActionPerformed(evt);
            }
        });

        abr.setText(")");
        abr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrActionPerformed(evt);
            }
        });

        jLabel2.setText("                                                                     Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abt, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ab1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ab7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ab4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(abequal, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aboo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ab5, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(ab8, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ab6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(ab9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(abg1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(abr, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(abp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(abmi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(abdo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ab2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ab3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(abb2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(absq1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(abl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ab2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abb2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(absq1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ab4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abg1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ab7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ab9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abmi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abdo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abequal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab2ActionPerformed
         // TODO add your handling code here:
          // add your handling code here:
       String aa = abt.getText()+ab2.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab2ActionPerformed

    private void ab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab1ActionPerformed
        // add your handling code here:
       String aa = abt.getText()+ab1.getText();
       abt.setText(aa);
     
    }//GEN-LAST:event_ab1ActionPerformed

    private void ab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab6ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab6.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab6ActionPerformed

    private void ab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab3ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab3.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab3ActionPerformed

    private void ab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab4ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab4.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab4ActionPerformed

    private void ab7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab7ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab7.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab7ActionPerformed

    private void ab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab5ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab5.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab5ActionPerformed

    private void aboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboActionPerformed
        // TODO add your handling code here:
       String aa = abt.getText()+abo.getText();
       abt.setText(aa);
    }//GEN-LAST:event_aboActionPerformed

    private void ab8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab8ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab8.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab8ActionPerformed

    private void abpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abpActionPerformed
        // TODO add your handling code here:
        action = "+";
        num1 = Double.valueOf(abt.getText());
        abt.setText("");
    }//GEN-LAST:event_abpActionPerformed

    private void abmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmiActionPerformed
           // TODO add your handling code here:
        action = "-";
        num1 = Double.valueOf(abt.getText());
        abt.setText("");
    }//GEN-LAST:event_abmiActionPerformed

    private void ab9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab9ActionPerformed
        // TODO add your handling code here:
         // add your handling code here:
       String aa = abt.getText()+ab9.getText();
       abt.setText(aa);
    }//GEN-LAST:event_ab9ActionPerformed

    private void abequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abequalActionPerformed
          // TODO add your handling code here:
           num2 = Double.valueOf(abt.getText());
           if ("+".equals(action))  {
               result = (double) (num1 + num2);
           }
           else if ("-".equals(action))  {
               result = (double) (num1 - num2);
           }
           else if ("*".equals(action))  {
               result = (double) (num1 * num2);
           }
           else if ("/".equals(action))  {
               result = (double) (num1 / num2);
           }
           abt.setText(String.valueOf(result));
    }//GEN-LAST:event_abequalActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abtActionPerformed

    private void abb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abb2ActionPerformed
        // TODO add your handling code here:
        action = "/";
        num1 = Double.valueOf(abt.getText());
        abt.setText("");
    }//GEN-LAST:event_abb2ActionPerformed

    private void abg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abg1ActionPerformed
        // TODO add your handling code here:
        action = "*";
        
       num1 = Double.valueOf(abt.getText());
        abt.setText("");
    }//GEN-LAST:event_abg1ActionPerformed

    private void abcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abcActionPerformed
        // TODO add your handling code here:
        abt.setText("");
    }//GEN-LAST:event_abcActionPerformed

    private void ablActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ablActionPerformed
           // TODO add your handling code here:
       String aa = abt.getText()+abl.getText();
       abt.setText(aa);
           
        
    }//GEN-LAST:event_ablActionPerformed

    private void abdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abdoActionPerformed
        // TODO add your handling code here:
       String aa = abt.getText()+abdo.getText();
       abt.setText(aa);
    }//GEN-LAST:event_abdoActionPerformed

    private void abooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abooActionPerformed
        // TODO add your handling code here:
       String aa = abt.getText()+aboo.getText();
       abt.setText(aa);
        
    }//GEN-LAST:event_abooActionPerformed

    private void absq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absq1ActionPerformed
        // TODO add your handling code here:
        num1 =Double.valueOf(abt.getText());
        double sqr = Math.sqrt(num1);
        abt.setText(String.valueOf(sqr));
    }//GEN-LAST:event_absq1ActionPerformed

    private void abrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrActionPerformed
        // TODO add your handling code here:
       String aa = abt.getText()+abr.getText();
       abt.setText(aa);
    }//GEN-LAST:event_abrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ab1;
    private javax.swing.JButton ab2;
    private javax.swing.JButton ab3;
    private javax.swing.JButton ab4;
    private javax.swing.JButton ab5;
    private javax.swing.JButton ab6;
    private javax.swing.JButton ab7;
    private javax.swing.JButton ab8;
    private javax.swing.JButton ab9;
    private javax.swing.JButton abb2;
    private javax.swing.JButton abc;
    private javax.swing.JButton abdo;
    private javax.swing.JButton abequal;
    private javax.swing.JButton abg1;
    private javax.swing.JButton abl;
    private javax.swing.JButton abmi;
    private javax.swing.JButton abo;
    private javax.swing.JButton aboo;
    private javax.swing.JButton abp;
    private javax.swing.JButton abr;
    private javax.swing.JButton absq1;
    private javax.swing.JTextField abt;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
